name: bysykkelen_stavanger
description: Use the city bikes in Stavanger without the tears

version: 1.2.0+1

environment:
  sdk: ">=2.3.0-dev <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^0.1.2

  dio: ^3.0.7
  dio_cookie_manager: ^1.0.0
  path_provider: ^1.4.5
  html: ^0.14.0+3
  flutter_bloc: ^2.1.1
  equatable: ^1.0.1
  google_maps_flutter: ^0.5.21+12
  firebase_crashlytics: ^0.0.4+8
  url_launcher: ^5.0.3
  geolocator: ^5.0.1
  kiwi: ^0.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
